### ISSUE TITLE
Significant space is being stripped.

### ISSUE THREAD

**Issue by peterolson** [hgourvest/node-xml-lite#5]
For example, if I parse

    <li>I've talked with a lot of <country>Cuba</country> people.</li>

it yields the following JSON

    { name: 'li',
      childs: [
        'I\'ve talked with a lot of ',
        { name: 'country', childs: ['Cuba'] },
        'people.'
      ]
    }

Notice how the space between "Cuba" and "people" is stripped out. Is this the intended behavior? Is there a workaround for this?

**Comment by hgourvest** [comment]
Thanks for the bug report, the original code was written in a different language for a specific purpose (xmpp), this why spaces was stripped.  published in npm registry as version 0.0.4

**Comment by peterolson** [comment]
Thanks for the quick fix, it seems to work now!
